services:
  - type: web
    name: koogwe-admin
    runtime: static
    rootDir: .
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://koogwe2-2-backend-1.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
